"""Add user role

Revision ID: 8b0297504afc
Revises: 
Create Date: 2022-03-22 17:51:07.830570

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8b0297504afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('order_statuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('user_roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('telegram_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('telegram_id')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('document_id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('waiting_for_at', sa.DateTime(), nullable=False),
                    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
                    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['order_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cells',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('is_open', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    meta = sa.MetaData(bind=op.get_bind())
    meta.reflect(only=("user_roles", "order_statuses"))
    op.bulk_insert(
        sa.Table('user_roles', meta),
        [
            {"id": 1, "name": "accountant"},
            {"id": 2, "name": "worker"},
            {"id": 3, "name": "service"},
        ],
    )
    op.bulk_insert(
        sa.Table('order_statuses', meta),
        [
            {"id": 1, "name": "Новая"},
            {"id": 2, "name": "Обрабатывается"},
            {"id": 3, "name": "Готова к выдачи"},
            {"id": 4, "name": "Выполнена"},
            {"id": 5, "name": "Отменена"},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cells')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('order_statuses')
    op.drop_table('documents')
    # ### end Alembic commands ###
