"""Invitations

Revision ID: feae4917b610
Revises: 8b0297504afc
Create Date: 2022-03-28 13:22:39.584261

"""
from alembic import op
import sqlalchemy as sa

from database.models import UserRole


# revision identifiers, used by Alembic.
revision = 'feae4917b610'
down_revision = '8b0297504afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    meta = sa.MetaData(bind=op.get_bind())
    meta.reflect(only=("invitations", ))
    op.bulk_insert(
        sa.Table('invitations', meta),
        [
            {"username": "Денис Добровольский", "role_id": UserRole.ACCOUNTANT, "token": "1234"},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###
